## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[["Attrition", "Department"]]
y_df

Attrition              Department
0          Yes                   Sales
1           No  Research & Development
2          Yes  Research & Development
3           No  Research & Development
4           No  Research & Development
...        ...                     ...
1465        No  Research & Development
1466        No  Research & Development
1467        No  Research & Development
1468        No                   Sales
1469        No  Research & Development

[1470 rows x 2 columns]

In [7]:
# Create a list of at least 10 column names to use as X data
X_data = ['Age',
          'DistanceFromHome',
          'Education',
          'HourlyRate',
          'JobLevel',
          'JobSatisfaction',
          'PercentSalaryHike',
          'WorkLifeBalance',
          'YearsAtCompany',
          'YearsSinceLastPromotion']


# Create X_df using your selected columns
X_df = attrition_df[X_data]

# Show the data types for X_df
X_df.dtypes


Age                        int64
DistanceFromHome           int64
Education                  int64
HourlyRate                 int64
JobLevel                   int64
JobSatisfaction            int64
PercentSalaryHike          int64
WorkLifeBalance            int64
YearsAtCompany             int64
YearsSinceLastPromotion    int64
dtype: object

In [14]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_df_train, X_df_test, y_df_train, y_df_test = train_test_split(X_df, y_df)


In [11]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary


In [15]:
# Create a StandardScaler
Scaler = StandardScaler()

# Fit the StandardScaler to the training data
Scaler.fit(X_df_train)

# Scale the training and testing data
X_df_train_scaled = Scaler.transform(X_df_train)
X_df_test_scaled = Scaler.transform(X_df_test)
X_df_train_scaled


array([[-0.23067455, -1.01055174,  0.09683219, ...,  0.34647767,
         0.64113105,  1.1846481 ],
       [-0.23067455,  0.09496912,  0.09683219, ...,  0.34647767,
         0.96694447,  1.1846481 ],
       [-0.23067455,  2.30601085,  1.06691464, ...,  0.34647767,
        -0.33630923,  0.56431918],
       ...,
       [-0.5582562 , -0.27353783,  2.03699709, ..., -1.0521245 ,
        -0.49921594, -0.67633865],
       [ 0.31529486, -0.39637348, -0.87325026, ...,  0.34647767,
         2.27019818,  1.49481255],
       [ 1.95320309, -0.64204478,  1.06691464, ...,  0.34647767,
        -0.66212266, -0.36617419]])

In [17]:
# Create a OneHotEncoder for the Department column
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
attrition_encoder = OneHotEncoder(sparse_output=False)
dept_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
dept_encoder.fit = dept_encoder.fit(y_df_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
dept_train_encoded = dept_encoder.transform(y_df_train[['Department']])
dept_test_encoded = dept_encoder.transform(y_df_test[['Department']])
dept_test_encoded


array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [18]:
# Create a OneHotEncoder for the Attrition column
attr_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
attr_fit_encoder = attr_encoder.fit(y_df_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
attr_train_encoded = attr_fit_encoder.transform(y_df_train[['Attrition']])
attr_test_encoded = attr_fit_encoder.transform(y_df_test[['Attrition']])
attr_test_encoded




array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

## Create, Compile, and Train the Model

In [71]:
# Find the number of columns in the X training data
number_columns = len(X_df_train.columns)

# Create the input layer
input_layer = layers.Input(shape=(10,))

# Create at least two shared layers
shared_layer1 = layers.Dense(64, activation='relu')(input_layer)
shared_layer2 = layers.Dense(128, activation='relu')(shared_layer1)

In [72]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_hidden = layers.Dense(32, activation='relu')(shared_layer2)

# Create the output layer
dept_output = layers.Dense(3, activation='softmax', name='dept_output')(dept_hidden)


In [73]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(32, activation='relu')(shared_layer2)

# Create the output layer
attr_output = layers.Dense(3, activation='sigmoid', name='attr_output')(attrition_hidden)


In [74]:
# Create the model
attr_model = Model(inputs=input_layer, outputs=[dept_output, attr_output])

# Compile the model
attr_model.compile(optimizer='adam',
              loss={'dept_output': 'categorical_crossentropy', 'attr_output': 'binary_crossentropy'},
              metrics={'dept_output': 'accuracy', 'attr_output': 'accuracy'})

# Summarize the model
attr_model.summary()

Model: "functional_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_5             │ (None, 10)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_19 (Dense)          │ (None, 64)             │            704 │ input_layer_5[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_20 (Dense)          │ (None, 128)            │          8,320 │ dense_19[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_21 (Dense)          │ (None, 32)             │          4,128 │ dense_20[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_22 (Dense)          │ (None, 32)             │          4,128 │ dense_20[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dept_output (Dense)       │ (None, 3)              │             99 │ dense_21[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attr_output (Dense)       │ (None, 3)              │             99 │ dense_22[0][0]         │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 17,478 (68.27 KB)

 Trainable params: 17,478 (68.27 KB)

 Non-trainable params: 0 (0.00 B)

In [75]:
# Train the model
batch_size = 32
epochs = 100

attr_model.fit(
    X_df_train_scaled,
    {
        'dept_output': dept_train_encoded,
        'attr_output': attr_train_encoded,
    },
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.2
)


Epoch 1/100


ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 2), output.shape=(None, 3)

In [77]:
# Evaluate the model with the testing data
test_results = attr_model.evaluate(np.array(X_df_test_scaled), {
        'dept_output': dept_test_encoded,
        'attr_output': attr_test_encoded,
    })
test_results

ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 2), output.shape=(None, 3)

In [ ]:
# Print the accuracy for both department and attrition


Department predictions accuracy: 0.5271739363670349
Attrition predictions accuracy: 0.8260869383811951


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1.
2.
3.